import { ToolMetadata } from "@/types/tools";

export const TOOLS: ToolMetadata[] = [
  // ==========================================
  // PDF TOOLS (9 Tools)
  // ==========================================
  {
    id: "compress-pdf",
    slug: "compress",
    title: "Compress PDF",
    shortDescription: "Reduce PDF file size while maintaining optimal visual clarity and sharpness.",
    fullDescription: "Shrink bloated PDF documents effortlessly. Uses smart compression algorithms to reduce file weight for rapid email sharing and web uploads without compromising text readability.",
    category: "pdf",
    route: "/pdf/compress",
    iconName: "Minimize2",
    badge: "Popular",
    seoTitle: "Free PDF Compressor Online — Reduce File Size Safely",
    seoDescription: "Compress PDF documents directly in your browser without sacrificing quality. 100% private, instant, and completely free.",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf optimizer", "online pdf compressor"],
    steps: [
      { title: "Select PDF", description: "Drag and drop or browse your device to choose your PDF file up to 50MB." },
      { title: "Choose Compression Level", description: "Select between Basic, Recommended, or Maximum compression presets." },
      { title: "Download Compressed File", description: "Save your freshly optimized, lightweight PDF instantly." },
    ],
    features: [
      "Zero upload to external servers — 100% in-browser",
      "Three distinct compression presets (Basic, Recommended, Maximum)",
      "Preserves searchable text, vector fonts, and layout",
      "Downscales oversized embedded photos safely",
    ],
    faqs: [
      { question: "Will compressing my PDF degrade text clarity?", answer: "No, text remains crisp vector paths and searchable. Only embedded raster images are downscaled if you select Recommended or Maximum presets." },
      { question: "Are my documents saved on any servers?", answer: "Never. All compression logic executes in your local browser sandbox via client-side WebAssembly and JavaScript." },
      { question: "What happens if compression doesn't reduce file size?", answer: "If your PDF is already efficiently compressed, the tool honestly notifies you and provides the original file so your document is never inflated." },
    ],
  },
  {
    id: "merge-pdf",
    slug: "merge",
    title: "Merge PDF",
    shortDescription: "Combine multiple PDF files into one clean, well-organized document.",
    fullDescription: "Merge multiple separate PDF files into a single master document. Reorder pages and files visually with simple drag-and-drop before finalizing your compilation.",
    category: "pdf",
    route: "/pdf/merge",
    iconName: "FilePlus2",
    badge: "Popular",
    seoTitle: "Free Online PDF Merger — Combine Multiple PDFs Easily",
    seoDescription: "Easily combine multiple PDF files into one single document. Fast, secure, client-side, and no file limit.",
    keywords: ["merge pdf", "combine pdfs", "join pdf files", "pdf binder online", "free pdf combiner"],
    steps: [
      { title: "Upload Multiple PDFs", description: "Select two or more PDF documents from your computer." },
      { title: "Reorder Documents", description: "Arrange the files in your desired chronological sequence." },
      { title: "Merge & Save", description: "Combine all pages into one single PDF and download immediately." },
    ],
    features: ["Intuitive drag-to-reorder interface", "Combine dozens of files at once", "No file size limits", "100% private in-browser processing"],
    faqs: [
      { question: "How many PDF files can I merge at once?", answer: "You can merge as many files as your device memory allows. Since it runs client-side, there are no artificial server limits." },
      { question: "Can I remove individual pages before merging?", answer: "Yes, you can inspect thumbnails and discard unnecessary pages before finalizing." },
    ],
  },
  {
    id: "split-pdf",
    slug: "split",
    title: "Split PDF",
    shortDescription: "Extract selected pages or split an entire PDF into separate standalone files.",
    fullDescription: "Separate specific pages or divide a multi-page PDF into independent files. Define custom page ranges or extract each page into individual documents.",
    category: "pdf",
    route: "/pdf/split",
    iconName: "Split",
    badge: "Essential",
    seoTitle: "Free PDF Splitter Online — Extract Pages from PDF",
    seoDescription: "Extract specific pages or break large PDF files into standalone documents instantly with total client-side privacy.",
    keywords: ["split pdf", "extract pdf pages", "separate pdf", "cut pdf", "free pdf divider"],
    steps: [
      { title: "Upload PDF", description: "Drop your multi-page document into the tool." },
      { title: "Select Ranges", description: "Specify page numbers (e.g. 1-3, 5, 8-12) or choose to split each page." },
      { title: "Export Files", description: "Download your extracted pages as a single ZIP or individual files." },
    ],
    features: ["Flexible range selection", "Live thumbnail visualizer", "Export single pages or ZIP package", "Instant local processing"],
    faqs: [
      { question: "Can I extract non-consecutive pages?", answer: "Yes, enter comma-separated ranges such as '1-4, 7, 9-11' to target exact pages." },
    ],
  },
  {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    shortDescription: "Convert JPG, PNG, and WebP images into a standardized, printable PDF file.",
    fullDescription: "Transform batches of images into a unified PDF booklet. Adjust margins, page orientations, and image fit options for crisp printing and easy archiving.",
    category: "pdf",
    route: "/pdf/jpg-to-pdf",
    iconName: "FileImage",
    badge: "Popular",
    seoTitle: "Convert JPG to PDF Online — High Quality & Free",
    seoDescription: "Convert your JPG photos and graphics into a polished PDF document. Customize orientation, margins, and page order locally.",
    keywords: ["jpg to pdf", "image to pdf converter", "convert photo to pdf", "batch jpg to pdf"],
    steps: [
      { title: "Select Images", description: "Choose one or multiple JPG or PNG images from your device." },
      { title: "Configure Page Setup", description: "Adjust page orientation (portrait/landscape) and margin padding." },
      { title: "Generate PDF", description: "Compile your images into a crisp PDF ready for export." },
    ],
    features: ["Auto-orient pages", "Custom margin controls", "Multi-image reordering", "Maintains original image resolution"],
    faqs: [
      { question: "Are my photos uploaded to a third-party server?", answer: "No, the conversion is handled purely via your device's web engine." },
    ],
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    shortDescription: "Extract high-resolution images or convert whole PDF pages into JPG pictures.",
    fullDescription: "Turn each PDF page into a high-DPI JPG image. Perfect for sharing document snippets on social media, presentations, or graphics software.",
    category: "pdf",
    route: "/pdf/pdf-to-jpg",
    iconName: "Images",
    badge: "Popular",
    seoTitle: "Convert PDF to JPG Online — High DPI Images",
    seoDescription: "Export pages from your PDF as crystal clear JPG pictures. Fast client-side rendering with no server uploads.",
    keywords: ["pdf to jpg", "convert pdf to images", "extract images from pdf", "pdf to picture"],
    steps: [
      { title: "Upload PDF", description: "Select the PDF file you want to turn into photos." },
      { title: "Set Resolution", description: "Choose standard 150 DPI or ultra-crisp 300 DPI output." },
      { title: "Download Images", description: "Save individual JPG files or grab everything in a single ZIP." },
    ],
    features: ["High-DPI rendering", "Extract embedded photos or full pages", "Bulk ZIP download", "Zero quality loss"],
    faqs: [
      { question: "What image quality can I expect?", answer: "We render up to 300 DPI for print-quality sharpness." },
    ],
  },
  {
    id: "word-to-pdf",
    slug: "word-to-pdf",
    title: "Word to PDF",
    shortDescription: "Convert DOCX documents into clean, universally readable PDF files.",
    fullDescription: "Transform Microsoft Word (.docx) files into immutable PDF documents. Preserves layout, headers, footnotes, and typographic styling accurately.",
    category: "pdf",
    route: "/pdf/word-to-pdf",
    iconName: "FileType",
    badge: "Essential",
    seoTitle: "Convert Word DOCX to PDF Online — Fast & Accurate",
    seoDescription: "Turn Word documents into clean PDFs without formatting shifts. Free, secure, and private.",
    keywords: ["word to pdf", "docx to pdf", "convert word document", "free docx to pdf"],
    steps: [
      { title: "Select Word File", description: "Pick any .docx file from your local storage." },
      { title: "Preview Layout", description: "Inspect the rendered pages for typographic alignment." },
      { title: "Download PDF", description: "Export the finalized PDF for universal distribution." },
    ],
    features: ["Accurate typography preservation", "Table and header support", "No Microsoft Office license required", "Clean vector output"],
    faqs: [
      { question: "Does this require Microsoft Office installed?", answer: "No, the parser compiles standard OpenXML DOCX files directly." },
    ],
  },
  {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    title: "PDF to Word",
    shortDescription: "Convert static PDF documents into editable Word (.docx) format.",
    fullDescription: "Extract text, paragraphs, and tables from your PDF files into an editable Microsoft Word document so you can modify text effortlessly.",
    category: "pdf",
    route: "/pdf/pdf-to-word",
    iconName: "FileSpreadsheet",
    badge: "Essential",
    seoTitle: "Convert PDF to Word DOCX Online — Editable Text",
    seoDescription: "Convert PDF files into fully editable Word documents. Reconstruct paragraphs, formatting, and tables seamlessly.",
    keywords: ["pdf to word", "pdf to docx", "make pdf editable", "convert pdf to doc"],
    steps: [
      { title: "Select PDF", description: "Choose the PDF containing text you need to edit." },
      { title: "Process Text & Layout", description: "Our parser detects paragraph structures and layout blocks." },
      { title: "Download DOCX", description: "Open and edit the converted Word file on any device." },
    ],
    features: ["Preserves paragraph formatting", "Extracts tables and lists", "Clean editable typography", "Privacy guaranteed"],
    faqs: [
      { question: "Can I edit the resulting file in Google Docs?", answer: "Yes, standard DOCX files open seamlessly in Google Docs, LibreOffice, and Word." },
    ],
  },
  {
    id: "pdf-to-excel",
    slug: "pdf-to-excel",
    title: "PDF to Excel",
    shortDescription: "Extract tables and tabular data from PDF invoices and reports into XLSX/CSV.",
    fullDescription: "Pull financial data, invoices, and table rows out of PDFs directly into clean Excel spreadsheets (.xlsx or .csv) for fast analysis.",
    category: "pdf",
    route: "/pdf/pdf-to-excel",
    iconName: "Table",
    badge: "New",
    seoTitle: "Extract PDF Tables to Excel Online — XLSX & CSV",
    seoDescription: "Convert tabular PDF files and financial statements into clean Excel spreadsheets without manual re-typing.",
    keywords: ["pdf to excel", "extract pdf tables", "pdf to xlsx", "pdf to csv", "invoice table extractor"],
    steps: [
      { title: "Upload PDF", description: "Provide the PDF containing tables or numerical reports." },
      { title: "Detect Tables", description: "Select the tabular zones or allow automatic table boundary detection." },
      { title: "Download Spreadsheet", description: "Save clean, structured XLSX or CSV data." },
    ],
    features: ["Auto table detection", "Cell data normalization", "Export to XLSX or CSV", "No confidential data sent to cloud"],
    faqs: [
      { question: "Can it handle multi-page tables?", answer: "Yes, continuous tables across pages are merged cleanly." },
    ],
  },
  {
    id: "pdf-unlock",
    slug: "pdf-unlock",
    title: "Unlock PDF",
    shortDescription: "Remove user passwords and security restrictions from protected PDF files.",
    fullDescription: "Strip printing, copying, and editing restrictions or remove known user passwords from your personal PDFs so you can use them without friction.",
    category: "pdf",
    route: "/pdf/pdf-unlock",
    iconName: "Unlock",
    badge: "Client-Side",
    seoTitle: "Unlock PDF Online — Remove Password & Restrictions",
    seoDescription: "Remove owner passwords and printing restrictions from your PDFs directly in your browser. Fast and completely safe.",
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf", "pdf permission remover"],
    steps: [
      { title: "Select Protected PDF", description: "Upload the encrypted document." },
      { title: "Enter Password", description: "Provide the document opening password if prompted." },
      { title: "Save Unlocked PDF", description: "Export an unconstrained version of your document." },
    ],
    features: ["Client-side decryption", "Removes print/copy restrictions", "Never exposes passwords over the network", "Instant generation"],
    faqs: [
      { question: "Is my password sent to a server?", answer: "No! The cryptographic decryption key is computed entirely in your local browser runtime." },
    ],
  },

  // ==========================================
  // IMAGE TOOLS (7 Tools)
  // ==========================================
  {
    id: "compress-image",
    slug: "compress-image",
    title: "Compress Image",
    shortDescription: "Optimize PNG, JPG, and WebP images with high quality and smaller file sizes.",
    fullDescription: "Cut down image file weight dramatically for faster website speeds and smaller file transfers. Uses browser-based lossy or lossless compression algorithms.",
    category: "image",
    route: "/image/compress-image",
    iconName: "FileArchive",
    badge: "Popular",
    seoTitle: "Free Image Compressor Online — Compress PNG, JPG & WebP",
    seoDescription: "Reduce image file size by up to 80% without visible quality loss. Real-time before/after slider, 100% in-browser.",
    keywords: ["compress image", "image optimizer", "shrink jpg", "reduce png size", "webp compressor"],
    steps: [
      { title: "Upload Images", description: "Drag and drop your pictures into the compressor." },
      { title: "Adjust Quality", description: "Use the live visual slider to dial in the ideal size-to-clarity ratio." },
      { title: "Download", description: "Save individual optimized images or download a ZIP package." },
    ],
    features: ["Live before/after comparison", "Lossy and lossless options", "Batch processing", "Zero server uploads"],
    faqs: [
      { question: "What formats are supported?", answer: "JPEG, PNG, WebP, AVIF, and GIF are supported." },
    ],
  },
  {
    id: "resize-image",
    slug: "resize-image",
    title: "Resize Image",
    shortDescription: "Change image dimensions by pixels or percentages with aspect ratio lock.",
    fullDescription: "Scale down or enlarge photos to exact pixel widths, heights, or percentage values. Maintain aspect ratios cleanly with smart bicubic resampling.",
    category: "image",
    route: "/image/resize-image",
    iconName: "Maximize",
    badge: "Essential",
    seoTitle: "Free Image Resizer Online — Scale Photos by Pixels or %",
    seoDescription: "Resize images to precise dimensions or aspect ratios. High-quality resampling directly inside your browser.",
    keywords: ["resize image", "image scaler", "change photo dimensions", "pixel resizer", "scale picture"],
    steps: [
      { title: "Choose Photo", description: "Upload any standard image file." },
      { title: "Set Dimensions", description: "Enter target width/height in pixels or adjust by percentage." },
      { title: "Export", description: "Download the resized image in your preferred format." },
    ],
    features: ["Aspect ratio locking", "Preset dimensions for social platforms", "High-quality bicubic interpolation", "Instant live preview"],
    faqs: [
      { question: "Will resizing blur my image?", answer: "Downscaling preserves crispness. Upscaling uses advanced smoothing to minimize pixelation." },
    ],
  },
  {
    id: "convert-image",
    slug: "convert-image",
    title: "Convert Image",
    shortDescription: "Convert between JPG, PNG, WebP, AVIF, BMP, and SVG formats seamlessly.",
    fullDescription: "Easily switch image formats for web optimization or print requirements. Convert PNG transparent graphics to JPG, or modernize assets into next-gen WebP.",
    category: "image",
    route: "/image/convert-image",
    iconName: "RefreshCw",
    badge: "Popular",
    seoTitle: "Free Image Converter Online — JPG, PNG, WebP & SVG",
    seoDescription: "Batch convert photos between popular image extensions in seconds. No watermarks, no registration, 100% private.",
    keywords: ["convert image", "png to jpg", "jpg to webp", "image format converter", "online photo converter"],
    steps: [
      { title: "Add Images", description: "Select the files you wish to convert." },
      { title: "Pick Output Format", description: "Select PNG, JPG, WebP, AVIF, or SVG." },
      { title: "Download Converted Files", description: "Grab the newly encoded graphics immediately." },
    ],
    features: ["Supports PNG, JPG, WebP, AVIF, SVG", "Transparency handling", "Batch multi-file conversion", "Client-side Canvas & OffscreenCanvas rendering"],
    faqs: [
      { question: "Can it handle transparent backgrounds?", answer: "Yes, when converting between transparent-compatible formats like PNG and WebP, transparency is retained." },
    ],
  },
  {
    id: "remove-background",
    slug: "remove-background",
    title: "Remove Background",
    shortDescription: "Erase photo backgrounds automatically with AI edge detection in your browser.",
    fullDescription: "Isolate subjects and cut out backgrounds for e-commerce products, headshots, and graphic design without requiring manual pen tools.",
    category: "image",
    route: "/image/remove-background",
    iconName: "Scissors",
    badge: "Popular",
    seoTitle: "Free Background Remover Online — Transparent PNG Cutouts",
    seoDescription: "Erase photo backgrounds instantly with smart client-side edge segmentation. Download crisp transparent PNGs.",
    keywords: ["remove background", "transparent background", "background eraser", "cut out image", "photo cutout"],
    steps: [
      { title: "Upload Image", description: "Provide a portrait, product photo, or graphic." },
      { title: "Automatic Cutout", description: "Edge detection identifies foreground subjects." },
      { title: "Download Transparent PNG", description: "Export your clean cutout with an alpha transparency channel." },
    ],
    features: ["Automatic foreground detection", "Transparent PNG output", "Adjustable mask brush", "Zero data transmission"],
    faqs: [
      { question: "What kind of photos work best?", answer: "Clear subjects with contrasting backgrounds yield the cleanest edges." },
    ],
  },
  {
    id: "crop-image",
    slug: "crop-image",
    title: "Crop Image",
    shortDescription: "Crop photos with freeform selection or standardized social media aspect ratios.",
    fullDescription: "Trim unwanted borders or center your subject with precision framing. Includes pre-calibrated aspect ratios for Instagram, YouTube thumbnails, avatars, and print.",
    category: "image",
    route: "/image/crop-image",
    iconName: "Crop",
    badge: "Essential",
    seoTitle: "Free Image Cropper Online — Aspect Ratios & Precise Framing",
    seoDescription: "Crop images visually with freeform handles or 16:9, 1:1, 4:5 presets. Instant preview and export.",
    keywords: ["crop image", "crop photo", "image trimmer", "social media photo crop", "aspect ratio crop"],
    steps: [
      { title: "Select Image", description: "Open the photo you want to crop." },
      { title: "Drag Crop Handles", description: "Position the boundary box or choose a preset like 1:1 or 16:9." },
      { title: "Export Cropped Photo", description: "Download the trimmed image in original resolution." },
    ],
    features: ["1:1, 4:3, 16:9, 9:16 presets", "Freeform custom bounds", "Grid alignment overlay", "Lossless cropping where possible"],
    faqs: [
      { question: "Can I rotate the image while cropping?", answer: "Yes, 90-degree rotations and horizontal flips are supported." },
    ],
  },
  {
    id: "image-to-pdf",
    slug: "image-to-pdf",
    title: "Image to PDF",
    shortDescription: "Compile collections of photos into a structured, easily shareable PDF.",
    fullDescription: "Turn photo albums, receipts, document scans, and portfolio graphics into a cohesive PDF document with clean page layouts.",
    category: "image",
    route: "/image/image-to-pdf",
    iconName: "FileCheck",
    badge: "Essential",
    seoTitle: "Convert Images to PDF Online — Multi-Page Photo Booklet",
    seoDescription: "Combine multiple photos into one sleek PDF document. Reorder slides, adjust margins, and export in seconds.",
    keywords: ["image to pdf", "photos to pdf", "combine pictures into pdf", "scans to pdf"],
    steps: [
      { title: "Add Pictures", description: "Choose any PNG, JPG, or WebP images." },
      { title: "Arrange Slides", description: "Drag thumbnails to establish the desired sequence." },
      { title: "Generate PDF", description: "Download your consolidated document." },
    ],
    features: ["Custom page padding", "Auto-orientation match", "High-resolution output", "100% private"],
    faqs: [
      { question: "Is there a limit to how many images I can add?", answer: "No server limits. Your browser's memory is the only ceiling." },
    ],
  },
  {
    id: "metadata-cleaner",
    slug: "metadata-cleaner",
    title: "Metadata Cleaner",
    shortDescription: "View and strip EXIF metadata, GPS locations, and camera tags from your photos.",
    fullDescription: "Protect your privacy before publishing photos online. Inspect and wipe hidden EXIF headers including camera model, exposure settings, timestamps, and GPS coordinates.",
    category: "image",
    route: "/image/metadata-cleaner",
    iconName: "ShieldCheck",
    badge: "Client-Side",
    seoTitle: "Free Image Metadata Cleaner — Strip EXIF & GPS Coordinates",
    seoDescription: "Inspect and remove sensitive EXIF data, GPS location tags, and device timestamps from photos before sharing.",
    keywords: ["exif cleaner", "remove metadata from photo", "strip gps from image", "photo privacy tool"],
    steps: [
      { title: "Upload Photo", description: "Select the photo you want to inspect." },
      { title: "View Hidden Tags", description: "Review embedded GPS coordinates, camera model, and dates." },
      { title: "Clean & Download", description: "Export a sanitized image stripped of all personal tracking data." },
    ],
    features: ["Detailed EXIF tag inspector", "One-click complete sanitization", "GPS coordinates viewer", "Zero server inspection"],
    faqs: [
      { question: "Why should I strip metadata before sharing photos?", answer: "Smartphones often embed your exact home or work GPS coordinates inside photo files." },
    ],
  },

  // ==========================================
  // DEVELOPER TOOLS (10 Tools)
  // ==========================================
  {
    id: "json-formatter",
    slug: "json-formatter",
    title: "JSON Formatter",
    shortDescription: "Beautify, indent, minify, and inspect JSON payloads with color-coded syntax.",
    fullDescription: "Format messy JSON data with clean 2-space or 4-space indentation. Features collapsible node trees, instant copy buttons, and validation warnings.",
    category: "developer",
    route: "/developer/json-formatter",
    iconName: "Braces",
    badge: "Popular",
    seoTitle: "Free JSON Formatter & Beautifier Online — Clean & Fast",
    seoDescription: "Beautify, format, and minify JSON strings with live syntax highlighting and interactive collapsible tree views.",
    keywords: ["json formatter", "json beautifier", "format json", "json pretty print", "minify json"],
    steps: [
      { title: "Paste JSON", description: "Paste your raw JSON code or drag in a .json file." },
      { title: "Select Spacing", description: "Pick 2-space, 4-space, tab indentation, or compact minification." },
      { title: "Copy or Download", description: "One-click copy the formatted result to your clipboard." },
    ],
    features: ["Interactive collapsible tree", "Syntax highlighting", "Minification toggle", "Large payload support"],
    faqs: [
      { question: "Is my JSON payload logged or saved?", answer: "Never. Parsing happens strictly in your browser's JavaScript engine." },
    ],
  },
  {
    id: "json-validator",
    slug: "json-validator",
    title: "JSON Validator",
    shortDescription: "Validate JSON syntax and pinpoint exact line numbers and characters with errors.",
    fullDescription: "Find syntax anomalies, missing trailing commas, unescaped quotes, and schema mistakes with detailed contextual line error diagnostics.",
    category: "developer",
    route: "/developer/json-validator",
    iconName: "CheckCircle2",
    badge: "Essential",
    seoTitle: "Free JSON Validator Online — Fix Broken JSON & Syntax Errors",
    seoDescription: "Validate JSON structure instantly. Pinpoints precise line numbers and character positions of syntax errors.",
    keywords: ["json validator", "check json syntax", "fix broken json", "json lint", "validate json online"],
    steps: [
      { title: "Enter Code", description: "Paste the JSON snippet you need to debug." },
      { title: "Instant Validation", description: "The parser tests structural integrity in real-time." },
      { title: "Review Fixes", description: "See precise line diagnostics and suggested fixes for syntax issues." },
    ],
    features: ["Pinpoint line & column error highlights", "Auto-fix common mistakes like trailing commas", "RFC 8259 compliance", "Instant feedback"],
    faqs: [
      { question: "Can it auto-repair minor JSON errors?", answer: "Yes, trailing commas and unquoted keys can be automatically corrected." },
    ],
  },
  {
    id: "jwt-decoder",
    slug: "jwt-decoder",
    title: "JWT Decoder",
    shortDescription: "Decode and inspect JSON Web Tokens headers, payloads, and expiration times safely.",
    fullDescription: "Decode JWT headers and claims without transmitting sensitive authentication tokens over third-party networks. Features live timestamp conversion to human-readable dates.",
    category: "developer",
    route: "/developer/jwt-decoder",
    iconName: "KeyRound",
    badge: "Client-Side",
    seoTitle: "Free JWT Decoder Online — Safely Inspect JSON Web Tokens",
    seoDescription: "Decode JWT headers and claims locally without sending authentication tokens across the internet. 100% private.",
    keywords: ["jwt decoder", "decode jwt", "jwt debugger", "inspect jwt token", "json web token parser"],
    steps: [
      { title: "Paste Token", description: "Paste your base64-encoded JWT token." },
      { title: "Inspect Claims", description: "View parsed Header, Payload, and Signature components." },
      { title: "Analyze Expiry", description: "Check token validity and human-readable expiration timestamps." },
    ],
    features: ["100% client-side security guarantee", "Human-readable Unix timestamp translation", "Expiry status badge (Active vs Expired)", "Color-coded token segments"],
    faqs: [
      { question: "Why is a client-side JWT decoder safer?", answer: "Many online decoders send your auth tokens to their servers. FileForge decodes tokens purely in your browser so tokens are never exposed." },
    ],
  },
  {
    id: "base64",
    slug: "base64",
    title: "Base64 Encoder / Decoder",
    shortDescription: "Encode text and binary data into Base64 format or decode strings back to plain text.",
    fullDescription: "Reliably convert strings, URLs, and data into ASCII Base64 format or decode existing hashes. Supports UTF-8 strings and URL-safe Base64 variants.",
    category: "developer",
    route: "/developer/base64",
    iconName: "Binary",
    badge: "Essential",
    seoTitle: "Free Base64 Encoder & Decoder Online — UTF-8 & URL-Safe",
    seoDescription: "Encode and decode Base64 strings, UTF-8 text, and binary data. Live two-way conversion with URL-safe options.",
    keywords: ["base64 encoder", "base64 decoder", "base64 encode online", "base64 string converter"],
    steps: [
      { title: "Input Text", description: "Type or paste your text or Base64 string." },
      { title: "Choose Direction", description: "Select Encode or Decode mode." },
      { title: "Copy Result", description: "Copy the converted output with one click." },
    ],
    features: ["Full UTF-8 unicode support", "URL-safe Base64 encoding mode", "Live instant calculation", "One-click copy to clipboard"],
    faqs: [
      { question: "Does this handle emojis and special characters?", answer: "Yes, full UTF-8 byte encoding is utilized to prevent character mangling." },
    ],
  },
  {
    id: "url-encoder",
    slug: "url-encoder",
    title: "URL Encoder / Decoder",
    shortDescription: "Percent-encode special characters for query strings or decode encoded URLs.",
    fullDescription: "Safely escape reserve characters in query parameters and URLs according to RFC 3986, or unescape percent-encoded URLs back to readable text.",
    category: "developer",
    route: "/developer/url-encoder",
    iconName: "Link2",
    badge: "Essential",
    seoTitle: "Free URL Encoder & Decoder Online — RFC 3986 Percent-Encoding",
    seoDescription: "Encode and decode URI strings and query parameters. Supports standard and component percent-encoding.",
    keywords: ["url encoder", "url decoder", "percent encoding", "uri encoder", "escape url online"],
    steps: [
      { title: "Paste URL", description: "Enter the full URL or query string component." },
      { title: "Toggle Mode", description: "Switch between Encode (percent encoding) and Decode." },
      { title: "Copy Output", description: "Grab the sanitized URL ready for HTTP requests." },
    ],
    features: ["encodeURI and encodeURIComponent support", "Decodes malformed query params", "Character statistics", "Instant live response"],
    faqs: [
      { question: "What is the difference between encodeURI and encodeURIComponent?", answer: "encodeURI preserves standard URL protocol dividers like http:// while encodeURIComponent escapes all punctuation." },
    ],
  },
  {
    id: "uuid-generator",
    slug: "uuid-generator",
    title: "UUID Generator",
    shortDescription: "Generate cryptographically secure v4 UUIDs / GUIDs in bulk with custom options.",
    fullDescription: "Create random, unique Version 4 UUIDs using the browser's crypto.getRandomValues API. Generate single keys or bulk batches with hyphens, uppercase, and quotes.",
    category: "developer",
    route: "/developer/uuid-generator",
    iconName: "Fingerprint",
    badge: "Popular",
    seoTitle: "Free UUID Generator Online — Bulk Cryptographic v4 GUIDs",
    seoDescription: "Generate random, unique v4 UUIDs instantly. Bulk creation, uppercase/lowercase options, with or without hyphens.",
    keywords: ["uuid generator", "guid generator", "v4 uuid", "random uuid", "bulk uuid generator"],
    steps: [
      { title: "Configure Quantity", description: "Select how many UUIDs you need (1 to 500)." },
      { title: "Set Formatting", description: "Choose uppercase, lowercase, with or without hyphens." },
      { title: "Copy or Download", description: "Copy all generated keys to your clipboard as a list or JSON array." },
    ],
    features: ["Cryptographically secure random values", "Bulk generation up to 500 at once", "Braces and quotes wrapping options", "Export as JSON, CSV, or plain text"],
    faqs: [
      { question: "Are these UUIDs truly unique?", answer: "Yes, v4 UUIDs have 122 bits of cryptographically strong randomness, making collisions virtually impossible." },
    ],
  },
  {
    id: "regex-tester",
    slug: "regex-tester",
    title: "RegEx Tester",
    shortDescription: "Test regular expressions with real-time matching, group captures, and cheatsheet.",
    fullDescription: "Debug complex regular expressions against sample test strings. Visualizes matches, capture groups, substitution results, and includes a quick cheatsheet.",
    category: "developer",
    route: "/developer/regex-tester",
    iconName: "FileCode2",
    badge: "Popular",
    seoTitle: "Free Online RegEx Tester & Debugger — Live Match Highlighter",
    seoDescription: "Test regular expressions with real-time match highlighting, capture groups breakdown, and regex cheatsheet.",
    keywords: ["regex tester", "regular expression tester", "regex debugger", "regex cheatsheet", "javascript regex"],
    steps: [
      { title: "Write Pattern", description: "Enter your regular expression and flags (g, i, m, s, u)." },
      { title: "Enter Test String", description: "Paste sample text you want to evaluate." },
      { title: "Inspect Matches", description: "See highlighted matches and capture group indexes." },
    ],
    features: ["Real-time match highlighting", "Group capture inspector", "Regex flags toggles", "Interactive syntax cheatsheet"],
    faqs: [
      { question: "What regex engine is used?", answer: "It runs the standard ECMAScript JavaScript RegExp engine." },
    ],
  },
  {
    id: "timestamp",
    slug: "timestamp",
    title: "Timestamp Converter",
    shortDescription: "Convert Unix epoch timestamps to human dates and parse dates to timestamps.",
    fullDescription: "Translate Unix epoch seconds and milliseconds into UTC, ISO-8601, and localized date-time strings, or generate timestamps from human dates.",
    category: "developer",
    route: "/developer/timestamp",
    iconName: "Clock",
    badge: "Essential",
    seoTitle: "Free Unix Timestamp Converter Online — Epoch to Human Date",
    seoDescription: "Convert Unix timestamps (seconds & milliseconds) to readable dates and relative times. Current epoch live ticker included.",
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "current unix epoch"],
    steps: [
      { title: "Enter Timestamp or Date", description: "Provide an epoch number or human readable date string." },
      { title: "View Formats", description: "See instant conversions in UTC, local time, ISO 8601, and relative time." },
      { title: "Copy Values", description: "Copy desired date formats with a single tap." },
    ],
    features: ["Live ticking current epoch clock", "Milliseconds and seconds auto-detection", "Timezone conversion", "Relative time calculation"],
    faqs: [
      { question: "How does it distinguish seconds from milliseconds?", answer: "10-digit numbers are parsed as seconds, while 13-digit numbers are parsed as milliseconds." },
    ],
  },
  {
    id: "color-converter",
    slug: "color-converter",
    title: "Color Converter",
    shortDescription: "Convert color values between HEX, RGB, HSL, CMYK, and CSS color formats.",
    fullDescription: "Translate web colors across HEX, RGB, HSL, HSV, and CSS variable formats. Features live visual color picker and WCAG contrast preview.",
    category: "developer",
    route: "/developer/color-converter",
    iconName: "Palette",
    badge: "Essential",
    seoTitle: "Free Color Converter Online — HEX, RGB, HSL & CMYK",
    seoDescription: "Convert color codes between HEX, RGB, HSL, and CMYK. Includes live visual color picker and contrast checker.",
    keywords: ["color converter", "hex to rgb", "rgb to hsl", "css color converter", "cmyk to rgb"],
    steps: [
      { title: "Input Color", description: "Type any HEX, RGB, or HSL code, or use the visual picker." },
      { title: "Inspect Conversions", description: "See values across all color spaces simultaneously." },
      { title: "Copy Codes", description: "Copy CSS ready values directly into your stylesheets." },
    ],
    features: ["Live visual color picker", "WCAG 2.1 accessibility contrast calculation", "CSS variable code snippets", "Alpha transparency support"],
    faqs: [
      { question: "Does it support alpha transparency?", answer: "Yes, 8-digit hex (#rrggbbaa) and rgba/hsla formats are supported." },
    ],
  },
  {
    id: "hash-generator",
    slug: "hash-generator",
    title: "Hash Generator",
    shortDescription: "Compute cryptographic hashes (SHA-256, SHA-512, SHA-1, MD5) directly in-browser.",
    fullDescription: "Calculate cryptographic checksums and message digests for strings and files. Uses the browser's native Web Crypto API for maximum execution speed.",
    category: "developer",
    route: "/developer/hash-generator",
    iconName: "Shield",
    badge: "Client-Side",
    seoTitle: "Free Hash Generator Online — SHA-256, SHA-512, SHA-1 & MD5",
    seoDescription: "Generate cryptographic hashes for text and files using native browser Web Crypto API. Fast, secure, and offline capable.",
    keywords: ["hash generator", "sha256 online", "sha512 generator", "md5 generator", "checksum calculator"],
    steps: [
      { title: "Enter Text or File", description: "Type text or drop a file to calculate its hash." },
      { title: "Choose Algorithms", description: "Calculate SHA-256, SHA-512, SHA-384, or SHA-1." },
      { title: "Copy Hash", description: "Copy uppercase or lowercase hex digests instantly." },
    ],
    features: ["Native Web Crypto API acceleration", "File checksum verification", "Supports SHA-256, SHA-512, SHA-384, SHA-1", "Zero network transmission"],
    faqs: [
      { question: "Is it safe to hash sensitive passwords or keys here?", answer: "Yes! Calculation is performed strictly within your machine's CPU/browser via Web Crypto." },
    ],
  },
];

export function getToolBySlug(slug: string): ToolMetadata | undefined {
  return TOOLS.find(
    (tool) =>
      tool.slug === slug ||
      (slug === "compress" && tool.slug === "compress-pdf") ||
      (slug === "compress-pdf" && tool.slug === "compress") ||
      (slug === "merge" && tool.slug === "merge-pdf") ||
      (slug === "merge-pdf" && tool.slug === "merge") ||
      (slug === "split" && tool.slug === "split-pdf") ||
      (slug === "split-pdf" && tool.slug === "split") ||
      (slug === "convert" && tool.slug === "convert-image") ||
      (slug === "convert-image" && tool.slug === "convert") ||
      (slug === "crop" && tool.slug === "crop-image") ||
      (slug === "crop-image" && tool.slug === "crop")
  );
}

export function getToolsByCategory(category: string): ToolMetadata[] {
  return TOOLS.filter((tool) => tool.category === category);
}

export function getCategoryCounts(): Record<string, number> {
  return TOOLS.reduce(
    (acc, tool) => {
      acc[tool.category] = (acc[tool.category] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );
}
